# for most SPAs w internal routing
[[redirects]]
  from = "https://api.nomics.com"
  to = "/index.html"
  status = 200

# paths covered
[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://api.nomics.com"
